name: Bounty - VSCode

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build extension
        run: npm run compile

      - name: Package VSIX
        run: npx @vscode/vsce package --no-dependencies

      - name: Publish GitHub release asset
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          title: "Latest VS Code Extension"
          prerelease: false
          files: "*.vsix"
