name: Release VS Code Extension

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.17

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build extension
        run: bun run compile

      - name: Package VSIX
        run: npx @vscode/vsce package --no-dependencies

      - name: Publish GitHub release asset
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          title: "Latest VS Code Extension"
          prerelease: false
          files: "*.vsix"
